---
# Create key file with <device>_key and encrypt devices

- name: Create key root file
  no_log: true
  copy:
      dest: "/etc/root_key"
      content: |
        {{ rootpassphrase }}
  when: gluster_infra_tangservers is defined

- name: Download the advertisement from tang server
  shell:
    cmd: curl -sfg "{{ item.url }}/adv" -o /etc/adv{{ index }}.jws
    warn: False
  loop: "{{ gluster_infra_tangservers }}"
  loop_control:
    index_var: index
  when: gluster_infra_tangservers is defined

- name: Bind tang server with clevis
  shell: clevis luks bind -f -k /etc/root_key -d  {{ rootdevice }} tang '{"url":"{{item.url}}", "adv":"/etc/adv{{ index }}.jws"}'
  loop: "{{ gluster_infra_tangservers }}"
  loop_control:
    index_var: index
  when: gluster_infra_tangservers is defined

# TODO Need to investigate how to configure incase of static deployment
- name: Add network entry on /etc/dracut.conf.d/clevis.conf
  blockinfile:
    path: /etc/dracut.conf.d/clevis.conf
    create: yes
    state: present
    block: |
      kernel_cmdline="ip={{ networkinterface }}:dhcp"
      omit_dracutmodules+="ifcfg"
      omit_dracutmodules+="network-legacy"
      add_dracutmodules+="clevis network-manager"
    marker: "# {mark} Entry for {{networkinterface}}"
  when: gluster_infra_tangservers is defined

- name: Execute dracut -vf to configure tang
  command: dracut -vf --regenerate-all
  when: gluster_infra_tangservers is defined

- name: Remove root_key file
  file:
    path: /etc/root_key
    state: absent
